# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 587e75cf6d2f3dfaee6747189db186355ee9d993bde306e322776158b4fadad637900ffb0faf4b379bf613d2da21155354d1459e050f805e620953668b345187

test:
  secret_key_base: 7a66fef683fce18843591f8585d6bf7e9c36ee05a2875ab428207f4194f5588db91a6b0f08e79a2d3ff6d92f023e39f15bc1292ffc143b344f721a8dc4d4feaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
